import streamlit as st
import json
import datetime
import os
from langchain_openai import ChatOpenAI
from langchain_core.tools import tool
from langchain import hub
from langchain.agents import create_react_agent, AgentExecutor

# --- 1. SETUP & CONFIG ---
st.set_page_config(page_title="AI Form Validator (Audit Mode)", layout="wide")
st.title("🕵️‍♂️ Agentic Form Validator (Full Audit)")
st.markdown("Validates **every field** against `extracted_rules.json` using **Gemma-2-9b**.")

# Sidebar
with st.sidebar:
    st.header("Local Model Settings")
    vllm_url = st.text_input("vLLM Base URL", value="http://localhost:8000/v1")
    model_name = st.text_input("Model Name", value="google/gemma-2-9b-it")
    st.info("Ensure vLLM is running: `vllm serve google/gemma-2-9b-it --max-model-len 8192 --dtype auto`")

# --- 2. DEFINE TOOLS (Mocked for Stability) ---

@tool
def check_event_existence(query: str):
    """Searches validity of a conference. Input: Event Name."""
    print(f"DEBUG: Checking event '{query}'")
    if "Time Travel" in query:
        return "❌ Event Not Found: No public record exists for this conference."
    elif "ICML" in query or "NeurIPS" in query or "CVPR" in query:
        return "✅ Event Confirmed: Verified major AI conference."
    else:
        return "⚠️ Ambiguous: Event found but dates unclear."

@tool
def calculate_funding_limit(total_cost_str: str):
    """Calculates the 2/3 funding limit. Input: '1000'."""
    try:
        clean_val = str(total_cost_str).replace("€", "").replace(",", "").strip()
        limit = float(clean_val) * (2/3)
        return str(round(limit, 2))
    except:
        return "Error: Invalid number."

@tool
def check_dates(date_string: str):
    """Checks 'APP_DATE|TRAVEL_DATE' logic."""
    try:
        parts = date_string.split("|")
        app_date = datetime.datetime.strptime(parts[0].strip(), "%Y-%m-%d")
        travel_date = datetime.datetime.strptime(parts[1].strip(), "%Y-%m-%d")
        if app_date < travel_date:
            return "✅ Valid (Before Travel)"
        else:
            return "❌ Invalid (Retroactive Application)"
    except:
        return "Error: Date format must be YYYY-MM-DD"

# --- 3. THE AUDITOR AGENT ---

def validate_form(form_data, rules_data):
    llm = ChatOpenAI(
        model=model_name,
        openai_api_key="EMPTY",
        openai_api_base=vllm_url,
        temperature=0
    )
    
    tools = [check_event_existence, calculate_funding_limit, check_dates]
    prompt = hub.pull("hwchase17/react")
    
    # --- CRITICAL CHANGE: The Audit Prompt ---
    context_input = f"""
    You are a Strict Auditor. 
    Perform a field-by-field compliance check on this form:
    {json.dumps(form_data)}

    Using ONLY these extracted rules:
    {json.dumps(rules_data)}

    YOUR MISSION:
    1. For the 'event_name' field: Use 'check_event_existence'.
    2. For the 'requested_amount' field: Use 'calculate_funding_limit' to compare against Total Cost.
    3. For dates: Use 'check_dates' (App Date vs Travel Start).
    4. For 'participation_type': Check against Eligibility Rules (Active vs Passive) manually.

    FINAL OUTPUT FORMAT (Markdown Table):
    | Field Name | User Input | Status (✅/❌/⚠️) | Rule Cited | Justification |
    |---|---|---|---|---|
    | Event Name | ... | ... | [Rule ID] | ... |
    | Travel Dates | ... | ... | [Rule ID] | ... |
    ... (Repeat for ALL fields)
    
    At the bottom, provide a "Final Verdict": APPROVED or REJECTED.
    """

    agent = create_react_agent(llm, tools, prompt)
    agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True, handle_parsing_errors=True)
    
    result = agent_executor.invoke({"input": context_input}) 
    return result["output"]

# --- 4. DATA LOADING ---

# Try to load the REAL rules generated by your previous script
def load_rules():
    try:
        with open("extracted_rules.json", "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        # Fallback if file is missing (The extracted rules you showed me earlier)
        return {
          "policy_name": "Richtlinien der Universität Passau (Fallback Mode)",
          "rules": [
            {"id": "R1", "category": "financial", "description": "Funding limited to max 2/3 of costs.", "logic_hint": "requested <= total * 0.66"},
            {"id": "R2", "category": "temporal", "description": "Application must be received BEFORE trip starts.", "logic_hint": "app_date < start_date"},
            {"id": "R3", "category": "eligibility", "description": "Only active participation (Lecture/Poster) is funded.", "logic_hint": "participation in [Poster, Lecture]"},
            {"id": "R4", "category": "verification", "description": "Event must be verified.", "logic_hint": "check_event_existence"}
          ]
        }

# --- 5. THE UI ---

col1, col2 = st.columns([1, 1])

with col1:
    st.subheader("📝 Applicant Data")
    default_form = """{
  "applicant": { "name": "Hans Muster", "status": "Doctoral Student" },
  "trip_details": {
    "event_name": "International Conference on Time Travel 2026",
    "location": "Berlin",
    "travel_start_date": "2026-02-01",
    "participation_type": "Passive Listener"
  },
  "submission_metadata": { "application_date": "2026-02-05" },
  "financials": { "total_costs_eur": 1000, "requested_amount_eur": 1000 }
}"""
    user_input = st.text_area("Form JSON", value=default_form, height=400)

with col2:
    st.subheader("📜 Active Policy Rules")
    active_rules = load_rules()
    st.json(active_rules, expanded=True)

if st.button("🚀 Run Compliance Audit"):
    if not vllm_url:
        st.error("Please enter a vLLM URL.")
    else:
        with st.spinner(f"Agent is auditing every field against {active_rules['policy_name']}..."):
            try:
                form_json = json.loads(user_input)
                report = validate_form(form_json, active_rules)
                
                st.success("Audit Complete!")
                st.markdown("### 📋 Final Compliance Matrix")
                st.markdown(report)
                
            except Exception as e:
                st.error(f"Error: {e}")